### ISSUE TITLE
Intel(R) Wi-Fi 6 AX200 160MHz wifi driver

### ISSUE THREAD

**Issue by fudio101** [itsmeshibintmz/Acer-Nitro-5-AN515-54-Big-Sur#5]
My laptop is AN515-54 54T0 with wifi is Intel(R) Wi-Fi 6 AX200 160MHz, then can i use this EFI for my driver

**Comment by itsmeshibintmz** [comment]
You should be fine I think, give it a try and update here.

**Comment by fudio101** [comment]
Everything are awesome. Thank you so much

**Comment by itsmeshibintmz** [comment]
You can find issues for such simple issues with community. They're great help both in discord and reddit. anyway happy to hear everything working fine. :)
