### ISSUE TITLE
Help with ComboJacker

### ISSUE THREAD

**Issue by vitorpedeo** [itsmeshibintmz/Acer-Nitro-5-AN515-54-Big-Sur#7]
First of all, I'd like to thank you for your help! Thanks to your repo I've managed to turn my Nitro 5 in a Hackintosh. Only problem I got so far is ComboJacker and I have two questions about it:

- How to install it? I've tried to run the install script but it won't run;
- Currently my headset microphone doesn't work. Will ComboJacker fix it?

I'm sorry if these are noob questions, but I'm very new to Hackintosh world 😀

**Comment by itsmeshibintmz** [comment]
To install combojack, plug in your headset, then open the install.sh file in Combojack_Installer folder.
It will fix the audio.


If found fixes, feel free to close the issue.

**Comment by vitorpedeo** [comment]
When I run the installer, these flags are shown:

![Screen Shot 2022-11-28 at 12 07 24](https://user-images.githubusercontent.com/49814532/204311843-ad83c193-e61c-489f-b06c-f57805c31559.png)

Do you know which one of these I should use?

**Comment by itsmeshibintmz** [comment]
Please send a screenshot of the Combojack_Installer folder(i don't have hackintosh setup now).

**Comment by vitorpedeo** [comment]
Here it is:

![Screen Shot 2022-11-28 at 12 34 41](https://user-images.githubusercontent.com/49814532/204318111-eef59145-9866-4687-bf19-5e39b7b201e1.png)

**Comment by vitorpedeo** [comment]
I figured out the problem: I was using `install` (macOS built-in command) instead of `./install.sh` 😐
Anyway, thanks for you time @itsmeshibintmz!
