### ISSUE TITLE
Reboots to picker

### ISSUE THREAD

**Issue by officialszcz** [itsmeshibintmz/Acer-Nitro-5-AN515-54-Big-Sur#9]
Hi after selecting usb.dmg and waiting to be loaded it reboots me to the picker no errors showing

**Comment by officialszcz** [comment]
Okay i added -v to boot-args and when i boot from usb and wait for it it gets kernel panic

**Comment by itsmeshibintmz** [comment]
you can add -v bootargs and know what error is holding u back.

**Comment by officialszcz** [comment]
> you can add -v bootargs and know what error is holding u back.

kernel panic

**Comment by itsmeshibintmz** [comment]
is your laptop is same model as mine? AN515-54? also have u done the changes as per given in the readme? 
1: Secure Boot turned off?
2: Generate SMBIOS as per device name (MacBook Pro 16,1)?
3: OC Clean Snapshot?
4: Done the pendrive formated to Non Bootable, Type : GPT, then copied the EFI and big sur files to respective folders?
5: Used recommended OpenCore release version?

**Comment by itsmeshibintmz** [comment]
Closing as there is no replies from the user.
